[build]
  command = "npm run build"
  publish = "dist"
  node_version = "18.0.0"

[build.environment]
  NODE_VERSION = "18.0.0"
  NPM_FLAGS = "--no-audit --no-fund"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript"

[[redirects]]
  from = "/d/*"
  to = "https://ziplockai-production.up.railway.app/files/:splat"
  status = 200
  force = true

[build.processing]
  skip_processing = false 